services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wedding_album
      POSTGRES_USER: wedding_album
      POSTGRES_PASSWORD: wedding_album
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

  backend:
    depends_on:
      - db
    environment:
      POSTGRES_DB: wedding_album
      POSTGRES_HOST: db
      POSTGRES_USER: wedding_album
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: wedding_album
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

volumes:
  postgres_data:
